### ISSUE TITLE
Create StorageClass during cluster creation automatically

### ISSUE THREAD

**Issue by dmytro-lazebnyi** [scalecube/spinless#22]
Would be good to have possibility to configure which `StorageClass` will be created during cluster creation.

Theoretically, should be done by installing this (not namespaced resource):

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: exchange
  name: aws-reclaimdel
parameters:
  fsType: ext4
  type: gp2
  zone: eu-west-2a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
